_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
dataset:
    value: StrongPassword.csv
model:
    value: XGBoost
param_grid:
    value:
        learning_rate:
            - 0.1
            - 0.2
        max_depth:
            - 3
            - 5
        n_estimators:
            - 50
            - 100
test_size:
    value: 0.2
